spring:
  data:
    mongodb:
      uri: mongodb+srv://nn0469971_db_user:vinh123456@pod.fzzmyug.mongodb.net/?appName=POD
      database: POD
      authentication-database: admin
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351
      access-token-expiration: 3600
      refresh-token-expiration: 604800
      refresh-token-secret: 782F413F4428472B4B6250655368566D597133743677397A24432646294A404E635266556A586E327235753877217A25432A462D4A614E645267556A586E3272

  datasource:
    url: jdbc:postgresql://localhost:5432/pod_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# DB Scheduler Configuration
db-scheduler:
  enabled: true
  # Tự động tạo bảng scheduled_tasks nếu chưa có
  auto-create-tables: true
  # Số lượng luồng chạy task (mặc định 10)
  threads: 5
  # Bao lâu quét DB 1 lần (mặc định 10s)
  polling-interval: 30s
  # Tên bảng (mặc định scheduled_tasks)
  table-name: scheduled_tasks

# Cloudinary Configuration
cloudinary:
  cloud-name: di5j3h6wi
  api-key: 227498933227112
  api-secret: 9arlZHQ4JV8y3eS6ZH18hca1Vqg

# Hugging Face Configuration (for Virtual Try-On)
huggingface:
  api-key:

# Gemini AI Configuration (for AI Chatbot)
gemini:
  api-key:
  model: gemini-2.5-flash

open:
  api:
    title: "C-Shop API"
    version: "v1.0.0"
    description: "api for pod_be of C-Shop project"
    url: "http://localhost:8080"
    description-server-url: "server-dev"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

